from rest_framework import status


#error status code
HTTP_400_BAD_REQUEST = status.HTTP_400_BAD_REQUEST

HTTP_401_UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED

HTTP_404_NOT_FOUND = status.HTTP_404_NOT_FOUND

HTTP_405_METHOD_NOT_ALLOWED = status.HTTP_405_METHOD_NOT_ALLOWED

HTTP_406_NOT_ACCEPTABLE = status.HTTP_406_NOT_ACCEPTABLE

HTTP_409_CONFLICT = status.HTTP_409_CONFLICT

HTTP_411_LENGTH_REQUIRED = status.HTTP_411_LENGTH_REQUIRED

HTTP_423_LOCKED = status.HTTP_423_LOCKED

HTTP_429_TOO_MANY_REQUESTS = status.HTTP_429_TOO_MANY_REQUESTS

HTTP_426_UPGRADE_REQUIRED = status.HTTP_426_UPGRADE_REQUIRED

HTTP_500_INTERNAL_SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR

HTTP_402_PAYMENT_REQUIRED = status.HTTP_402_PAYMENT_REQUIRED

HTTP_413_REQUEST_ENTITY_TOO_LARGE = status.HTTP_413_REQUEST_ENTITY_TOO_LARGE

#success status code
HTTP_200_OK = status.HTTP_200_OK

HTTP_201_CREATED = status.HTTP_201_CREATED

HTTP_202_ACCEPTED = status.HTTP_202_ACCEPTED

HTTP_204_NO_CONTENT = status.HTTP_204_NO_CONTENT

HTTP_500_INTERNAL_SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR
